using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace UniLaunch.CodeGenerator;

[Generator]
public class ViewModelGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // No init required for this generator
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var syntaxTrees = context.Compilation.SyntaxTrees;

        foreach (var syntaxTree in syntaxTrees)
        {
            var root = syntaxTree.GetRoot();
            var semanticModel = context.Compilation.GetSemanticModel(syntaxTree);

            foreach (var classDeclaration in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
                if (classSymbol == null || !ShouldGenerateViewModel(classSymbol))
                    continue;

                var code = GenerateViewModelCode(classSymbol);
                context.AddSource($"{classSymbol.Name}ViewModel.Properties.g.cs", SourceText.From(code, Encoding.UTF8));
            }
        }
    }

    private static bool ShouldGenerateViewModel(ISymbol classSymbol) =>
        classSymbol.GetAttributes().Any(attr => attr.AttributeClass!.Name.EndsWith("GenerateViewModelAttribute"));

    private string GenerateViewModelCode(INamedTypeSymbol classSymbol)
    {
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        var attributeArgs = classSymbol.GetAttributes()
            .First(attr => attr.AttributeClass!.Name.EndsWith("GenerateViewModelAttribute"))
            .ConstructorArguments;

        var modelType = attributeArgs[0]
            .Value as INamedTypeSymbol;

        var controlType = (attributeArgs[1]
                .Value as INamedTypeSymbol
            )?.ToString() ?? "TextBlock";

        var propertiesToCreateForImpl = modelType!.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(symbol => symbol.SetMethod != null && symbol.Name != "Name");
        var propertiesToGenerateForParent = modelType.BaseType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(symbol => symbol.SetMethod != null && symbol.Name != "Name");

        var allProperties = propertiesToCreateForImpl
            .Concat(propertiesToGenerateForParent);
        var properties = allProperties
            .Select(GenerateProperty);
        var className = classSymbol.Name;
        var propertyDefinitions = string.Join("\n", properties);

        var baseNameProperty = modelType.BaseType?
            .GetMembers()
            .OfType<IPropertySymbol>()
            .FirstOrDefault(m => m.Name == "Name");
        var nameProperty = modelType.GetMembers()
            .OfType<IPropertySymbol>()
            .FirstOrDefault(m => m.Name == "Name");
        var namePropertySetter = nameProperty?.IsReadOnly == false
                                 || baseNameProperty?.IsReadOnly == false
            ? "_model.Name = value;"
            : "";

        var propertyWatcher = GeneratePropertiesToWatch(allProperties.ToList());

        var code = $$"""
                     //----------------------
                     // <auto-generated>
                     //     Generated by UniLaunch.CodeGeneration.  DO NOT EDIT!
                     // </auto-generated>
                     //----------------------
                     using System;
                     using ReactiveUI;
                     using Avalonia.Controls;
                     using UniLaunch.UI.CodeGeneration;
                     using System.Collections.ObjectModel;
                     using {{modelType.ContainingNamespace.ToDisplayString()}};

                     namespace {{namespaceName}}
                     {
                         public partial class {{className}} : BaseEntityViewModel
                         {
                             private {{modelType}} _model = null;
                     
                             {{propertyDefinitions}}
                             
                             public override Type UserControl => typeof({{controlType}});
                             
                             public override string Name => _model.Name;
                     
                             public override string NameProperty {
                                 set {
                                    {{namePropertySetter}}
                                    this.RaisePropertyChanged(nameof(NameProperty));
                                 }
                                 get => _model.Name;
                             }
                     
                             /// <summary>
                             /// Create empty few model
                             /// </summary>
                             public {{className}}()
                             {
                                InitViewModel();
                             }
                             
                             partial void InitViewModel();
                             
                             /// <summary>
                             /// Create view model from model
                             /// </summary>
                             public {{className}}({{modelType}} model)
                             {
                                InitViewModel();
                                this._model = model;
                             }
                             
                             /// <summary>
                             /// Get the model from view model
                             /// </summary>
                             public override {{modelType}} Model {
                                get => this._model;
                             }
                             
                             {{propertyWatcher}}
                         }
                     }
                     """;

        return CSharpSyntaxTree.ParseText(code)
            .GetRoot()
            .NormalizeWhitespace()
            .GetText()
            .ToString();
    }

    private string GeneratePropertiesToWatch(List<IPropertySymbol> properties)
    {
        var nameOfProperties = properties
            .Where(p => p != null)
            .Select(p => $"nameof({p.Name}Property)")
            .Append("nameof(NameProperty)")
            .ToList();

        return $"""
                private string[] _propertiesToWatchForChanges = [{string.Join(",", nameOfProperties)}];
                public override string[] PropertiesToWatchForChanges => _propertiesToWatchForChanges;
                """;
    }

    private string GenerateProperty(IPropertySymbol propertySymbol)
    {
        var propertyName = propertySymbol.Name;

        return $$"""
                 /// <summary>
                 /// Property for ViewModel binding to {{propertyName}}
                 /// </summary>
                 public {{propertySymbol.Type.ToDisplayString()}} {{propertyName}}Property
                         {
                             set {
                                _model.{{propertyName}} = value;
                                this.RaisePropertyChanged(nameof({{propertyName}}Property));
                             }
                             get => _model.{{propertyName}};
                         }
                 """;
    }
}