version: "2.1"

orbs:
  win: circleci/windows@5.0.0
  github-utils: trustedshops-public/github-utils@1.1.2

executors:
  dotnet-sdk:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
  macos:
    macos:
      xcode: "14.2.0"

jobs:
  unit-test:
    executor: dotnet-sdk
    steps:
      - checkout
      - run:
          name: Run tests
          command: dotnet test
  
  build-windows:
    executor:
      name: win/default
      size: medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            choco install -y make curl innosetup
            curl https://dot.net/v1/dotnet-install.ps1 -o dotnetInstall.ps1
            ./dotnetInstall.ps1 -Channel 8.0.1xx
            make windows-build
      - store_artifacts:
          path: ./dist
  
  build-macos:
    executor: macos
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            brew install make create-dmg
            echo 'export DOTNET_ROOT=$HOME/.dotnet' >> $BASH_ENV 
            echo 'export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools' >> $BASH_ENV 
            curl -L https://dot.net/v1/dotnet-install.sh --output dotnetInstall
            chmod +x dotnetInstall
            ./dotnetInstall -Channel 8.0.1xx
      - run:
          name: Build MacOS artifacts
          command: |
            make macos-build
      - store_artifacts:
          path: ./dist
  build-linux:
    executor: dotnet-sdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apt-get update && \
            apt-get install -y --no-install-recommends make docker-ce-cli
      - run: 
          name: Run make
          command: |
            make linux-build

workflows:
  main:
    jobs:
      - unit-test
      - build-macos
      - build-windows
      - build-linux
