//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniLaunch.UI.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UniLaunch.UI.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PlaceholderNewRuleSet {
            get {
                return ResourceManager.GetString("PlaceholderNewRuleSet", resourceCulture);
            }
        }
        
        public static string AppMenuOpenFile {
            get {
                return ResourceManager.GetString("AppMenuOpenFile", resourceCulture);
            }
        }
        
        public static string AppMenuSaveFile {
            get {
                return ResourceManager.GetString("AppMenuSaveFile", resourceCulture);
            }
        }
        
        public static string AppMenuSaveToFile {
            get {
                return ResourceManager.GetString("AppMenuSaveToFile", resourceCulture);
            }
        }
        
        public static string AppMenuExit {
            get {
                return ResourceManager.GetString("AppMenuExit", resourceCulture);
            }
        }
        
        public static string AppMenuUnsavedChangesToolTip {
            get {
                return ResourceManager.GetString("AppMenuUnsavedChangesToolTip", resourceCulture);
            }
        }
        
        public static string NavTabsTitleTargets {
            get {
                return ResourceManager.GetString("NavTabsTitleTargets", resourceCulture);
            }
        }
        
        public static string NavTabsTitleRulesets {
            get {
                return ResourceManager.GetString("NavTabsTitleRulesets", resourceCulture);
            }
        }
        
        public static string NavTabsTitleEntries {
            get {
                return ResourceManager.GetString("NavTabsTitleEntries", resourceCulture);
            }
        }
        
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        public static string AboutWindowDescription {
            get {
                return ResourceManager.GetString("AboutWindowDescription", resourceCulture);
            }
        }
        
        public static string AboutWindowLabelVersion {
            get {
                return ResourceManager.GetString("AboutWindowLabelVersion", resourceCulture);
            }
        }
        
        public static string AboutWindowLabelCreatedBy {
            get {
                return ResourceManager.GetString("AboutWindowLabelCreatedBy", resourceCulture);
            }
        }
        
        public static string AboutWindowLabelLicense {
            get {
                return ResourceManager.GetString("AboutWindowLabelLicense", resourceCulture);
            }
        }
        
        public static string LocaleNameDE {
            get {
                return ResourceManager.GetString("LocaleNameDE", resourceCulture);
            }
        }
        
        public static string LocaleNameEN {
            get {
                return ResourceManager.GetString("LocaleNameEN", resourceCulture);
            }
        }
        
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        public static string SettingsWindowConnectivityCheckTitle {
            get {
                return ResourceManager.GetString("SettingsWindowConnectivityCheckTitle", resourceCulture);
            }
        }
        
        public static string SettingsWindowConnectivityCheckLabelEndpoint {
            get {
                return ResourceManager.GetString("SettingsWindowConnectivityCheckLabelEndpoint", resourceCulture);
            }
        }
        
        public static string SettingsWindowConnectivityCheckLabelTimeout {
            get {
                return ResourceManager.GetString("SettingsWindowConnectivityCheckLabelTimeout", resourceCulture);
            }
        }
        
        public static string SettingsWindowEditorSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsWindowEditorSettingsTitle", resourceCulture);
            }
        }
        
        public static string SettingsWindowEditorSettingsLabelThemeVariant {
            get {
                return ResourceManager.GetString("SettingsWindowEditorSettingsLabelThemeVariant", resourceCulture);
            }
        }
        
        public static string SettingsWindowEditorSettingsLabelThemeVariantSystem {
            get {
                return ResourceManager.GetString("SettingsWindowEditorSettingsLabelThemeVariantSystem", resourceCulture);
            }
        }
        
        public static string SettingsWindowEditorSettingsLabelThemeVariantDark {
            get {
                return ResourceManager.GetString("SettingsWindowEditorSettingsLabelThemeVariantDark", resourceCulture);
            }
        }
        
        public static string SettingsWindowEditorSettingsLabelThemeVariantLight {
            get {
                return ResourceManager.GetString("SettingsWindowEditorSettingsLabelThemeVariantLight", resourceCulture);
            }
        }
        
        public static string SettingsWindowEditorSettingsLabelLanguage {
            get {
                return ResourceManager.GetString("SettingsWindowEditorSettingsLabelLanguage", resourceCulture);
            }
        }
        
        public static string SettingsWindowEditorSettingsLabelCheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("SettingsWindowEditorSettingsLabelCheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        public static string SettingsWindowEditorSettingsLabelYes {
            get {
                return ResourceManager.GetString("SettingsWindowEditorSettingsLabelYes", resourceCulture);
            }
        }
        
        public static string SettingsWindowEditorSettingsLabelNo {
            get {
                return ResourceManager.GetString("SettingsWindowEditorSettingsLabelNo", resourceCulture);
            }
        }
        
        public static string AutoStartEntryControlLabelTarget {
            get {
                return ResourceManager.GetString("AutoStartEntryControlLabelTarget", resourceCulture);
            }
        }
        
        public static string AutoStartEntryControlLabelRuleset {
            get {
                return ResourceManager.GetString("AutoStartEntryControlLabelRuleset", resourceCulture);
            }
        }
        
        public static string AutoStartEntryControlLabelContainsRules {
            get {
                return ResourceManager.GetString("AutoStartEntryControlLabelContainsRules", resourceCulture);
            }
        }
        
        public static string RuleSetControlLabelName {
            get {
                return ResourceManager.GetString("RuleSetControlLabelName", resourceCulture);
            }
        }
        
        public static string RuleSetControlLabelRules {
            get {
                return ResourceManager.GetString("RuleSetControlLabelRules", resourceCulture);
            }
        }
        
        public static string AlwaysRuleControlDisplayName {
            get {
                return ResourceManager.GetString("AlwaysRuleControlDisplayName", resourceCulture);
            }
        }
        
        public static string TimeRuleControlPreposition {
            get {
                return ResourceManager.GetString("TimeRuleControlPreposition", resourceCulture);
            }
        }
        
        public static string WeekdayRuleControlLabelMonday {
            get {
                return ResourceManager.GetString("WeekdayRuleControlLabelMonday", resourceCulture);
            }
        }
        
        public static string WeekdayRuleControlLabelTuesday {
            get {
                return ResourceManager.GetString("WeekdayRuleControlLabelTuesday", resourceCulture);
            }
        }
        
        public static string WeekdayRuleControlLabelWednesday {
            get {
                return ResourceManager.GetString("WeekdayRuleControlLabelWednesday", resourceCulture);
            }
        }
        
        public static string WeekdayRuleControlLabelThursday {
            get {
                return ResourceManager.GetString("WeekdayRuleControlLabelThursday", resourceCulture);
            }
        }
        
        public static string WeekdayRuleControlLabelFriday {
            get {
                return ResourceManager.GetString("WeekdayRuleControlLabelFriday", resourceCulture);
            }
        }
        
        public static string WeekdayRuleControlLabelSaturday {
            get {
                return ResourceManager.GetString("WeekdayRuleControlLabelSaturday", resourceCulture);
            }
        }
        
        public static string WeekdayRuleControlLabelSunday {
            get {
                return ResourceManager.GetString("WeekdayRuleControlLabelSunday", resourceCulture);
            }
        }
        
        public static string GenericTargetControlLabelDependencies {
            get {
                return ResourceManager.GetString("GenericTargetControlLabelDependencies", resourceCulture);
            }
        }
        
        public static string ExecutableTargetControlLabelTargetName {
            get {
                return ResourceManager.GetString("ExecutableTargetControlLabelTargetName", resourceCulture);
            }
        }
        
        public static string ExecutableTargetControlLabelExecutablePath {
            get {
                return ResourceManager.GetString("ExecutableTargetControlLabelExecutablePath", resourceCulture);
            }
        }
        
        public static string ExecutableTargetControlLabelArguments {
            get {
                return ResourceManager.GetString("ExecutableTargetControlLabelArguments", resourceCulture);
            }
        }
        
        public static string WaitForNetworkConnectivityToggleControlLabelWaitForNetwork {
            get {
                return ResourceManager.GetString("WaitForNetworkConnectivityToggleControlLabelWaitForNetwork", resourceCulture);
            }
        }
        
        public static string AppFileTargetControlLabelName {
            get {
                return ResourceManager.GetString("AppFileTargetControlLabelName", resourceCulture);
            }
        }
        
        public static string AppFileTargetControlLabelAppFile {
            get {
                return ResourceManager.GetString("AppFileTargetControlLabelAppFile", resourceCulture);
            }
        }
        
        public static string DialogUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("DialogUpdateAvailableTitle", resourceCulture);
            }
        }
        
        public static string DialogUpdateAvailableDescription {
            get {
                return ResourceManager.GetString("DialogUpdateAvailableDescription", resourceCulture);
            }
        }
        
        public static string DialogUpdateAvailableAction {
            get {
                return ResourceManager.GetString("DialogUpdateAvailableAction", resourceCulture);
            }
        }
    }
}
